FROM node:18.17.0-alpine AS base
WORKDIR /app
COPY ./package*.json ./
RUN npm install

FROM base AS build
WORKDIR /app
COPY . .
RUN npm run build

FROM node:18.17.0-alpine AS production
ENV NODE_ENV production
RUN npm install -g serve
WORKDIR /srv
COPY --from=build /app/build ./
CMD serve -l 3000 -s .