FROM node:18.17.0-alpine AS base
WORKDIR /app
COPY ./package*.json ./
RUN npm install

FROM base AS build
WORKDIR /app
COPY . .
RUN npm run build

FROM node:18.17.0-alpine AS production
ENV NODE_ENV production
RUN npm install -g serve
WORKDIR /srv
COPY --from=dist /app/dist ./
CMD serve -s .