services:
  frontend:
    image: crypto-frontend:dev
    container_name: frontend_service
    build: .
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - VITE_API_HOST=http://localhost:3000
    ports:
      - "5173:5173"