name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache-dependency-path: frontend/package-lock.json

      - name: Update lock file
        run: cd frontend && npm install --package-lock

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Build
        run: cd frontend && npm run build

      - name: Set Environment Variables
        uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          teamId: ${{ secrets.VERCEL_ORG_ID }}
          projectName: crypto-frontend
          envVariableKeys: VITE_API_HOST
        env:
          VITE_API_HOST: ${{ secrets.VITE_API_HOST }}
          TARGET_VITE_API_HOST: production # comma delimited, one of [production, preview, development]
          TYPE_VITE_API_HOST: encrypted # one of [plain, encrypted]

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          path: './frontend'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: --prod